name: ci

on: [push, workflow_dispatch]

env:
  NODE_OPTIONS: --max-old-space-size=3200
  CC_TEST_REPORTER_ID: 59622194cc44d91d2d1d239dffbe6af31e8cb985e6e6369c0743b67ad2cc8713

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v4, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v4, with: { node-version: 'lts/*', cache: 'yarn' } }
      - run: yarn --frozen-lockfile
      - run: yarn dev-lib tsc
      - name: test
        run: |
          curl -s -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          yarn test
          ./cc-test-reporter after-build -t lcov
